
### Create client – Alice
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Alice Smith",
    "email": "alice@example.com"
}

###

### Create client – Bob
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Bob Jones",
    "email": "bob@example.com"
}

###

### Create account for Alice (replace client_id with Alice's id)
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "f4a498a7-5f0c-4ead-8f3b-d5a48264a2b1"
}

###

### Create account for Bob (replace client_id with Bob's id)
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "8b38afc4-1e47-4f9d-a2f5-ef12dc0c3c34"
}

###

### Create a transaction  (Alice → Bob, uses seed account IDs)
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "f8df753c-3b58-43aa-8016-12aaa4f1ea3e",
    "account_id_to": "0216ea38-524f-4e85-8743-d484a8f7538e",
    "amount": 100
}
